# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Reality Virtually Hackathon"
email: "team@realityvirtuallyhack.com"
description: "Calling everyone to create, learn and explore new and yet to be known VR and AR applications at the MIT Media Lab, Cambridge, Massachusetts, USA"
baseurl: ""
url: "https://realityvirtuallyhack.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: ""
organizerAlternateName: ""
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/mitmedialab.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: ""
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {calltoaction: true, permalink: "/#", text: "Get Updates", onclick: "register()", style: "color:#5dccb7;" , id: "registrationButton"}
# - {permalink: "#", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/hackathon/", text: "Hackathon"}
 - {link: "/about/", text: "About", hasDropdown: false}
 - {link: "https://pastevents.realityvirtuallyhack.com/", text: "Past Events" , 2016event: "#2016", hasDropdown: true }
# - {link: "http://www.realityvirtuallyhack.com/about-2016/", text: "RV2016"}
 - {link: "/team/", text: "Team", hasDropdown: false}
 - {link: "/sponsors/", text: "Sponsors", hasDropdown: false}

# Hero Block
heroImage: "abstract-virtual-reality.png"
heroTitle: "Reality Virtually Hackathon"
heroDescription: "@ the MIT Media Lab"
eventDate: "January 17-21<sup>st</sup>, 2019"
typeoutTextValues: '" Hackathon"'
typeoutFallback: "Season"
notifyMeButtonText: "Notify me when applications open"


# About Block
aboutTitle: "About Reality Virtually"
aboutHeaderBody: "The Reality Virtually Hackathon brings together interdisciplinary minds to explore the application of virtual reality and augmented reality technologies for building new experiences. We encourage developers, designers, engineers, artists, coders, experts, sound designers, storytellers, students, creatives, and imaginative AR/VR enthusiasts to apply."
aboutBlock:
 - {title: "Hackathon", image: "mitmedialab_hackathon.png", text: "The biggest immersive hackathon in the world is in the works. During a full five days, you will meet new people, form interdisciplinary teams, brainstorm and build AR/VR experiences and applications that redefine immersive technologies. We will have passionate and skilled mentors to help teams ideate, build and deliver their projects. Vetted and qualified judges will pick the best among a variety of categories. Sponsors will provide an abundance of technology platforms to work with: ARCore, ARKit, Vive, Gear VR , Hololens, and more." }
 - {title: "Conference", image: "mitmedialab_outer.png", text: "We will be hosting some of the world’s brightest minds to present topics relevant to AR/VR in a series of lectures and panels.  You can check out last year’s conference program <a href=\"https://pastevents.realityvirtuallyhack.com/conference\">here</a>." }
 - {title: "Workshops", image: "mitmedialab_workshops.jpg", text: "The hackathon will lead with a full day of workshops to get people ready to contribute to their team’s project. Come and tame your favorite technology. You can check out last year’s workshop schedule here." }
aboutMainBodyTitle: "Reality Virtually Hackathon returning to the MIT Media Lab, January 17–21, 2019"
aboutMainBodyBold: "AR/VR designers, developers, sound engineers, graphic artists, domain experts, and enthusiasts  invited to apply"
aboutMainBody: "<p>The Reality Virtually Hackathon is a purpose-built hackathon community of 400 participants selected from approximately 1,600 applicants to create original cross reality (XR) work. The hackathon is a learning experience that deepens the extended community’s understanding of how immersive technology can be applied to solve real-world problems. It takes place in the iconic MIT Media Lab, overlooking the breathtaking Boston skyline in the heart of Cambridge’s tech scene-- a setting that inspires the most creative work.</p><p> The guiding principles of the Reality, Virtually hackathon rest on interdisciplinary teams. Networking with new people, and exposure to new ideas and skill-building workshops set the stage for impassioned individuals to fuse into teams, with each team sharing a common vision to implement an impactful, original idea. The distillation of the approximately 400 unaffiliated people into teams of up to five individuals produces a creative dynamic, resulting in unique applications of immersive technologies to create ingenious, never-before-seen XR experiences and applications.</p><p> The distribution of participants will be 50% students and 50% working practitioners. We will meet or exceed last year’s diversity and inclusion results of 43% female with 53 races/ethnicities and countries of origin represented.</p><p> If the Reality, Virtually Hackathon holds true to past events, it will have life-changing impact. For example, Gautham Pasupuleti, a 2017 participant, developed his winning submission into a UNICEF-supported pediatric eye care and healthcare project for under-resourced geographies. Two-time hackathon winner Jackie Assar joined Google’s hardware team along with her teammate Anish Dhesikan, who is now a software engineer on the Google AR team. Companies formed from winning teams, such as 2016 winner Waypoint RX, have gone on to be acquired (Waypoint was recently acquired by PTC.)</p><p> Last year’s hackathon–the largest ever immersive event–attracted sponsors such as Samsung, Microsoft, AT&T, Google, HTC VIVE, HP, Autodesk, and Ricoh’s Theta camera group. <a href='https://arvr-hackathon-2017.devpost.com/submissions'>Last year’s submissions</a> represented fields such as education, healthcare, entertainment and storytelling, commerce and industry, and human/social interaction.</p>"


#Recap
recapBackgroundImage: ""
recapText: "Watch last years recap"

#Quotes from Sponsors
quotesFromSponsorsBackground: ""
quotesFromSponsors:
 - { quote: "Many of the things that you saw created here you might see on a virtual store shelf next year or even sooner." , sponsor: "Richard Marks Head of PlayStation Magic Lab"}
 - { quote: "The quality of ideas, diversity, and scale of the Reality Virtually Hackathon has been impressive. It's a thrill to be supporting the VR and AR communities at the grassroots level.", sponsor: "Nick Nigam, Venture Investor at Samsung's Global InnovationCenter"}
 - { quote: "Very interesting to walk around, great diversity, the most diverse hackathon I have ever been too.", sponsor: "Benjamin Nelson, Sr. Product Marketing Manager at AT&T"}


#Last Years Winners
winnersTitle: "2017 Hackathon Grand Prize Winners"

#PrizeCategories
prizeCategoriesBackgroundImage: "statistic.jpg"
prizeCategoriesTitle: "Prize Categories"
prizeCategoriesSub: "Possible hackathon prize categories"
prizeCategories:
 - { name: "Architecture, Engineering, and Construction"}
 - { name: "Automotive"}
 - { name: "Healthcare and Medicine"}
 - { name: "Gaming and Entertainment"}
 - { name: "Advertising"}
 - { name: "Education"}
# - { category: "Other vertical or vertical AR or VR that participants are passionate about"}


# Statistic Block
statisticBlockImage: "statisticsB.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: ""}
 - {count: "43", specialCharacter: "", info: "%", detail: "diversity goal met"}
 - {count: "75", specialCharacter: "+", info: "", detail: "projects available under open source license"}
 - {count: "40", specialCharacter: "", info: "mentors", detail: "better than a 10:1 participant to mentor ratio"}


statisticBlockImageB: "judges.jpg"
statisticBlockB:
 - {count: "25", specialCharacter: "", info: "judges"}
 - {count: "20", specialCharacter: "+", info: "workshop leads", detail: ""}
 - {count: "5", specialCharacter: "+", info: "Days", detail: "of learning, building, new people and new ideas"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "MIT MEDIA LAB"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "75 Amherst St"
eventAddressLocality: "Cambridge"
eventAddressLocalityRegion: "Massachusetts"
eventPostalCode: "02139"
eventAddressCountry: "US"
#eventStartTime: "2014-10-25T10:00"
#eventDoorTime: "09:00"
#eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "42.360684, -71.087317"
mapCenterCoordinates: "42.360684, -71.090367"
mapMobileCenterCoordinates: "42.360684, -71.090367"


# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: ""
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "#", icon: "google-plus"}
 - {link: "https://twitter.com/realityvrhack", icon: "twitter" }
 - {link: "https://www.facebook.com/realityvrhack/", icon: "facebook"}
 - {link: "https://www.instagram.com/realityvrhack/", icon: "instagram", fontawesome: "instagram"}
# - {permalink: "/feed.xml", icon: "rss"}


footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.media.mit.edu/", text: "MIT Media Lab"}
#   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:team@realityvirtuallyhack.com", text: "team@realityvirtuallyhack.com"}
 -
#  title: "FAQ"
  links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Organizing Team"
aboutUs: "The Creating Reality Hackathon is organized by a dynamic team of industry experts, developers, executives, and students, reaching many facets of the VR|AR community."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "medialab.png"
directionDetailsTitle: ""
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="https://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: ""
hackathonRows:
 - {title: "New this year", image: "hackathon-0.png", details: "Participants in previous years have asked for more time to build, so we’ve added a fifth day to the schedule to expand creative time to almost 60 hours. Another request by participants was the opportunity to see the submissions built by other teams. On the last day of the hackathon, beginning right after the awards ceremony, the Insider Expo will begin, where participants can visit other teams’ tables to see their creative and original work. The hackathon will close with a public expo for the Boston/Cambridge AR/VR technology community at large."}
 - {title: "Workshops", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Mentors", image: "hackathon-2.png", details: "Skilled in XR design, development, and with domain expertise in verticals such as healthcare and medicine, 40 mentors will help teams throughout the hackathon, coalescing individuals into teams, ideating, creating, troubleshooting, debugging, and refining for submission to the judges."}
 - {title: "Our Mission and Commitment to Diversity", image: "hackathon-2.png", details: "The Reality, Virtually Hackathon is a platform that cultivates unique innovations in the field of immersive technology. Our mission is the creation of a community of inclusion, where imaginative minds across all dimensions of diversity can collaborate to inspire innovation and build better together."}




# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"



##ADMIN
applicationsEnpointUSA: ""
applicationsEnpointEUROPE: ""
applicationsEnpointTEST: "https://script.google.com/macros/s/AKfycbyaWiGh56mFtSNXcUMkj4vPjX9Y7TaU6N7toA53FVQTVDdkyX-5/exec"